language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-filesystem-dev libboost-test-dev
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
